create table
  public.program_interests (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    phone text not null,
    email text not null,
    program_id uuid not null,
    constraint program_interests_pkey primary key (id),
    constraint public_program_interests_program_id_fkey foreign key (program_id) references programs (id)
  ) tablespace pg_default;

alter table public.program_interests enable row level security;

create policy "Only admin can access programs_interests"
  on program_interests for select
  using ( is_claims_admin() );

create policy "Only admins can create new programs_interests"
  on program_interests for insert
  with check ( true );

create policy "Only admins can update programs_interests"
  on program_interests for update
  using ( is_claims_admin() );

create policy "Only admins and delete programs_interests"
  on program_interests for delete
  using (is_claims_admin());