create table
  public.worksheets (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    published boolean not null default false,
    "startDate" date not null,
    "endDate" date not null,
    days jsonb null,
    constraint worksheets_pkey primary key (id)
  );

alter table public.worksheets enable row level security;

create policy "Public worksheets are viewable by authenticated."
  on worksheets for select
  using ( auth.uid() IS NOT NULL );

create policy "Only admins can create new worksheets"
  on worksheets for insert
  with check ( is_claims_admin() );

create policy "Only admins can update worksheets"
  on worksheets for update
  using ( is_claims_admin() );