import { FREE_PRODUCT } from './subscriptions'
import { APP_ENTITLEMENTS, TEntitlementsInfo } from 'goal-models'

export const FAKE_ENTITLEMENTS: TEntitlementsInfo = {
    [APP_ENTITLEMENTS.COMMUNITY_GROUPS_ACCESS]: {
        identifier: APP_ENTITLEMENTS.COMMUNITY_GROUPS_ACCESS,
        isActive: true,
        willRenew: true,
        periodType: '',
        latestPurchaseDate: '',
        latestPurchaseDateMillis: 0,
        originalPurchaseDate: '',
        originalPurchaseDateMillis: 0,
        expirationDate: null,
        expirationDateMillis: null,
        store: 'UNKNOWN_STORE',
        productIdentifier: FREE_PRODUCT.identifier,
        isSandbox: false,
        unsubscribeDetectedAt: null,
        unsubscribeDetectedAtMillis: null,
        billingIssueDetectedAt: null,
        billingIssueDetectedAtMillis: null,
        ownershipType: 'UNKNOWN',
    },
    [APP_ENTITLEMENTS.FOLLOW_COMMUNITY_RESULTS]: {
        identifier: APP_ENTITLEMENTS.FOLLOW_COMMUNITY_RESULTS,
        isActive: true,
        willRenew: true,
        periodType: '',
        latestPurchaseDate: '',
        latestPurchaseDateMillis: 0,
        originalPurchaseDate: '',
        originalPurchaseDateMillis: 0,
        expirationDate: null,
        expirationDateMillis: null,
        store: 'UNKNOWN_STORE',
        productIdentifier: FREE_PRODUCT.identifier,
        isSandbox: false,
        unsubscribeDetectedAt: null,
        unsubscribeDetectedAtMillis: null,
        billingIssueDetectedAt: null,
        billingIssueDetectedAtMillis: null,
        ownershipType: 'UNKNOWN',
    },
    [APP_ENTITLEMENTS.SAVE_WORKOUT_RESULT]: {
        identifier: APP_ENTITLEMENTS.SAVE_WORKOUT_RESULT,
        isActive: true,
        willRenew: true,
        periodType: '',
        latestPurchaseDate: '',
        latestPurchaseDateMillis: 0,
        originalPurchaseDate: '',
        originalPurchaseDateMillis: 0,
        expirationDate: null,
        expirationDateMillis: null,
        store: 'UNKNOWN_STORE',
        productIdentifier: FREE_PRODUCT.identifier,
        isSandbox: false,
        unsubscribeDetectedAt: null,
        unsubscribeDetectedAtMillis: null,
        billingIssueDetectedAt: null,
        billingIssueDetectedAtMillis: null,
        ownershipType: 'UNKNOWN',
    },
    [APP_ENTITLEMENTS.WEEKLY_WORKOUT_ACCESS]: {
        identifier: APP_ENTITLEMENTS.WEEKLY_WORKOUT_ACCESS,
        isActive: true,
        willRenew: true,
        periodType: '',
        latestPurchaseDate: '',
        latestPurchaseDateMillis: 0,
        originalPurchaseDate: '',
        originalPurchaseDateMillis: 0,
        expirationDate: null,
        expirationDateMillis: null,
        store: 'UNKNOWN_STORE',
        productIdentifier: FREE_PRODUCT.identifier,
        isSandbox: false,
        unsubscribeDetectedAt: null,
        unsubscribeDetectedAtMillis: null,
        billingIssueDetectedAt: null,
        billingIssueDetectedAtMillis: null,
        ownershipType: 'UNKNOWN',
    },
}
